[package]
name = "DBL"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.79"
serde = { version = "1.0.214", features = ["derive"] }
temp-dir = "0.1.14"
directories = "5.0.1"
mockall = "0.13.1"
serial_test = "3.2.0"
uuid = { version = "1.11.0", features = ["v4"] }
