[package]
name = "Final_project_test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.79"
serde = { version = "1.0.214", features = ["derive"] }
temp-dir = "0.1.14"
directories = "5.0.1"